### ISSUE TITLE
Empty docker content digest causing service creation/update impossible - No 2

### ISSUE THREAD

**Issue by stefanmichalk** [nohaapav/swarmpit#676]
Hi,

we want to use swarmpit for our system, but there's an error, we don't get rid of.

`Service creation failed. rpc error: code = InvalidArgument desc = ContainerSpec: "***/package-name:main@" is not a valid repository/tag`

We searched the issues and there was the same issue, but no solution for this (https://github.com/swarmpit/swarmpit/issues/312)

We're using Docker Hub (private), Auth went well, swarmpit searches the Hub, shows the Repo, etc.
We tagged the package with 'latest', 'main', etc. and nothing seems to work.

We tried swarmpit v1.9, also Edge (currently v1.10-850a7f9). No changes at all.

Our Github Action is pretty simple

```
name: create and push docker image to Docker Hub

on:
  push:
    branches: [ 'main', 'staging', 'develop' ]

env:
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
```

The `latest` for each branch is currently just a test ;-)

**Fun fact** 
If we create a stack, it can pull the image, create a service, everything is fine. But when you edit the service and toggle Auto-Deploy for example, you will run in the same error message as above.

Does anyone run in the same problem and can provide a solution for this?

All the best
Stefan
